version: "3.8"

services:
  app:
    image: app
    build: ./math_site/
    container_name: app
    restart: always
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - math-network
  
  frontend:
    image: frontend
    build: ./frontend/
    container_name: frontend
    restart: always
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    networks:
      - math-network
  
  nginx:
    image: nginx_app
    build: ./nginx/
    ports:
    - 80:80
    depends_on:
      - app
    networks:
      - math-network

networks:
  math-network:
    driver: bridge
